### ISSUE TITLE
Naming Conflict

### ISSUE THREAD

**Issue by stretch07** [datkat21/pluto-web-os#33]

**Comment by datkat21** [comment]
# ![https://pluto.zeon.dev](https://raw.githubusercontent.com/zeondev/pluto/main/assets/images/banner.svg)

Hello, @stretch07.

Thank you for bringing this to our attention. We were unaware of the existence of your Pluto project and it's indeed a coincidence that we've been working on projects with the same name and similar goals. We understand the effort you've put into your Pluto project over the years.

We don't want to cause any conflict due to the naming. We are open to discussions on how we can resolve this issue but changing the name of our project isn't an option at this moment. We appreciate your offer to give us access to your Pluto codebase and your willingness to contribute to our project, but we will sadly decline.

We do have some reasons why we cannot change our name:

- Pluto is a project that has been actively in development since early 2023, we started development on [replit.com](https://replit.com), and moved [that Repl](https://replit.com/@ktat/pluto-indev?v=1#core.js) on to GitHub, where our repository is now. The name was originally used for our older project in 2022 which was later renamed to Saturn, as we couldn't find a suitable appealing logo for Pluto that isn't just a circle.
- Saturn is another completely different Webtop that is now in retirement with different goals to Pluto, so switching to the other project's name would just confuse our user base.
- The name Pluto keeps our Zeon naming collection consistent with the space theme, as every project we have made has a space name and we currently don't have a lot of available names.

We appreciate you for reaching out, and we are looking forward to finding a way to solve this that respects the work that both of us have done.

Best,   
@datkat21 and @ItsLap from @zeondev
